---
-
  become: true
  gather_facts: false
  hosts: appserver
  tasks:
    -
      name: "Docker Dependencies"
      apt:
        update_cache: true
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
    -
      name: "Docker GPG Key"
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
    -
      name: "Docker Repository"
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu focal stable"
    -
      name: "Docker Engine"
      apt:
        update-cache: true
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
    -
      name: "Python Dependencies"
      apt:
        name: python3-pip
        state: latest
        update_cache: true
      become: true
    -
      name: "Docker SDK for Python"
      pip:
        name: docker
    -
      name: "Docker Group Add [username]"
      shell: "sudo usermod -aG docker {{user}}"
  vars:
    user: ubuntu # Fill in desired username
