--- 
- 
  become: true
  gather_facts: false
  hosts: appserver
  tasks: 
    - 
     apt: 
        name: nginx
        state: latest
      name: "Installing nginx"
    - 
      name: "Sending Proxy Configuration"
      ansible.builtin.copy: 
        dest: /etc/nginx/sites-enabled
        src: ~/config/rproxy/
    - 
      name: "Restarting nginx service"
      service: 
        enabled: true
        name: nginx
        state: restarted

