--- 
- 
  become: true
  gather_facts: false
  hosts: appserver
  tasks: 
    - 
     name: Re-create a redis container
      community.docker.docker_container:
      name: nginx-test
      image: nginx:alpine
      state: present
      recreate: true
      ports:
        - 8080:80
    - 
      name: "Sending Proxy Configuration"
      ansible.builtin.copy: 
        dest: /etc/nginx/sites-enabled
        src: ~/config/rproxy/
    - 
      name: "Restarting nginx service"
      service: 
        enabled: true
        name: nginx
        state: restarted

