---
-
  become: true
  gather_facts: false
  hosts: appserver
  tasks:
    -
     name: "Installing nginx"
     apt:
       name: nginx
       state: latest
       update_cache: yes
    -
      name: start nginx
      service:
        name: nginx
        state: started

