--- 
- 
  become: true
  gather_facts: false
  hosts: appserver
  tasks: 
    - 
      name: "Creating User [username]"
      ansible.builtin.user: 
        groups: sudo
        name: "{{usernem}}"
        password: "{{passwot}}"
        state: present
        system: false
        append: yes
        home: /home/({usernem})

  vars: 
   - usernem: "ade" # Fill in your desired username
   - passwot: "$6$TaSzosd339yI$Hh/y4YtxryoOnrESQZ2U61ebCSh/DvCYGatsmZ/TnZlC4RJdkLbGturqL0GTzu1wBBBk5VAuU.ymEuByDbJoa1" # whois encrypted password

